(() => {
function createGridSlots(rows, cols) {
  const slots = [];
  for (let y = 0; y < rows; y += 1) {
    for (let x = 0; x < cols; x += 1) {
      slots.push({ x, y, w: 1, h: 1 });
    }
  }
  return slots;
}

const PRESETS = [
  {
    id: "mosaic-top1-bottom2",
    label: "Oben 1, unten 2",
    rows: 2,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 2, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 1, y: 1, w: 1, h: 1 },
    ],
  },
  {
    id: "mosaic-top2-bottom1",
    label: "Oben 2, unten 1",
    rows: 2,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 1, y: 0, w: 1, h: 1 },
      { x: 0, y: 1, w: 2, h: 1 },
    ],
  },
  {
    id: "mosaic-left1-right2",
    label: "Links 1, rechts 2",
    rows: 2,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 1, h: 2 },
      { x: 1, y: 0, w: 1, h: 1 },
      { x: 1, y: 1, w: 1, h: 1 },
    ],
  },
  {
    id: "mosaic-left2-right1",
    label: "Links 2, rechts 1",
    rows: 2,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 1, y: 0, w: 1, h: 2 },
    ],
  },
  {
    id: "mosaic-top1-bottom3",
    label: "Oben 1, unten 3",
    rows: 2,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 3, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 1, y: 1, w: 1, h: 1 },
      { x: 2, y: 1, w: 1, h: 1 },
    ],
  },
  {
    id: "mosaic-top3-bottom1",
    label: "Oben 3, unten 1",
    rows: 2,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 1, y: 0, w: 1, h: 1 },
      { x: 2, y: 0, w: 1, h: 1 },
      { x: 0, y: 1, w: 3, h: 1 },
    ],
  },
  {
    id: "story-left-main",
    label: "Story links, rechts 2",
    rows: 2,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 1, h: 2 },
      { x: 1, y: 0, w: 2, h: 1 },
      { x: 1, y: 1, w: 2, h: 1 },
    ],
  },
  {
    id: "story-right-main",
    label: "Story rechts, links 2",
    rows: 2,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 2, h: 1 },
      { x: 0, y: 1, w: 2, h: 1 },
      { x: 2, y: 0, w: 1, h: 2 },
    ],
  },
  {
    id: "story-center-main",
    label: "Story Mitte, Seiten 4",
    rows: 2,
    cols: 3,
    slots: [
      { x: 1, y: 0, w: 1, h: 2 },
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 2, y: 0, w: 1, h: 1 },
      { x: 2, y: 1, w: 1, h: 1 },
    ],
  },
  {
    id: "hero-plus-4",
    label: "Hero + 4",
    rows: 3,
    cols: 4,
    slots: [
      { x: 0, y: 0, w: 4, h: 2 },
      { x: 0, y: 2, w: 1, h: 1 },
      { x: 1, y: 2, w: 1, h: 1 },
      { x: 2, y: 2, w: 1, h: 1 },
      { x: 3, y: 2, w: 1, h: 1 },
    ],
  },
  {
    id: "panorama-plus-3",
    label: "Panorama + 3",
    rows: 2,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 3, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 1, y: 1, w: 1, h: 1 },
      { x: 2, y: 1, w: 1, h: 1 },
    ],
  },
  {
    id: "mosaic-5-asym",
    label: "Mosaik 5 asymmetrisch",
    rows: 3,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 2, h: 2 },
      { x: 2, y: 0, w: 1, h: 1 },
      { x: 2, y: 1, w: 1, h: 1 },
      { x: 0, y: 2, w: 1, h: 1 },
      { x: 1, y: 2, w: 2, h: 1 },
    ],
  },
  {
    id: "social-cover-split",
    label: "Social Cover Split",
    rows: 2,
    cols: 6,
    slots: [
      { x: 0, y: 0, w: 1, h: 2 },
      { x: 1, y: 0, w: 2, h: 2 },
      { x: 3, y: 0, w: 3, h: 2 },
    ],
  },
  {
    id: "grid-4x4-center-circle",
    label: "4x4 mit Kreis Mitte",
    rows: 4,
    cols: 4,
    slots: [
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 1, y: 0, w: 1, h: 1 },
      { x: 2, y: 0, w: 1, h: 1 },
      { x: 3, y: 0, w: 1, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 1, y: 1, w: 2, h: 2, shape: "circle" },
      { x: 3, y: 1, w: 1, h: 1 },
      { x: 0, y: 2, w: 1, h: 1 },
      { x: 3, y: 2, w: 1, h: 1 },
      { x: 0, y: 3, w: 1, h: 1 },
      { x: 1, y: 3, w: 1, h: 1 },
      { x: 2, y: 3, w: 1, h: 1 },
      { x: 3, y: 3, w: 1, h: 1 },
    ],
  },
  {
    id: "hex-3",
    label: "Hex 3",
    rows: 2,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 1, h: 1, shape: "hexagon" },
      { x: 1, y: 0, w: 1, h: 1, shape: "hexagon" },
      { x: 0, y: 1, w: 1, h: 1, shape: "hexagon" },
    ],
  },
	{
	  id: "hex-6",
	  label: "Hex 6",
	  rows: 2,
	  cols: 3,
	  slots: [
		{ x: 0, y: 0, w: 1, h: 1, shape: "hexagon" },
		{ x: 1, y: 0, w: 1, h: 1, shape: "hexagon" },
		{ x: 2, y: 0, w: 1, h: 1, shape: "hexagon" },
		{ x: 0, y: 1, w: 1, h: 1, shape: "hexagon" },
		{ x: 1, y: 1, w: 1, h: 1, shape: "hexagon" },
		{ x: 2, y: 1, w: 1, h: 1, shape: "hexagon" },
	  ],
	},
  {
    id: "hex-7-honeycomb",
    label: "Hex 7 Wabe",
    rows: 3,
    cols: 3,
    slots: [
      { x: 1, y: 0, w: 1, h: 1, shape: "hexagon" },
      { x: 0, y: 1, w: 1, h: 1, shape: "hexagon" },
      { x: 1, y: 1, w: 1, h: 1, shape: "hexagon" },
      { x: 2, y: 1, w: 1, h: 1, shape: "hexagon" },
      { x: 0, y: 2, w: 1, h: 1, shape: "hexagon" },
      { x: 1, y: 2, w: 1, h: 1, shape: "hexagon" },
      { x: 2, y: 2, w: 1, h: 1, shape: "hexagon" },
    ],
  },
  {
    id: "hex-9-honeycomb",
    label: "Hex 9 Wabe",
    rows: 3,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 1, h: 1, shape: "hexagon" },
      { x: 1, y: 0, w: 1, h: 1, shape: "hexagon" },
      { x: 2, y: 0, w: 1, h: 1, shape: "hexagon" },
      { x: 0, y: 1, w: 1, h: 1, shape: "hexagon" },
      { x: 1, y: 1, w: 1, h: 1, shape: "hexagon" },
      { x: 2, y: 1, w: 1, h: 1, shape: "hexagon" },
      { x: 0, y: 2, w: 1, h: 1, shape: "hexagon" },
      { x: 1, y: 2, w: 1, h: 1, shape: "hexagon" },
      { x: 2, y: 2, w: 1, h: 1, shape: "hexagon" },
    ],
  },
  {
    id: "corner-2x2-top-left",
    label: "3x3 Ecke: 2x2 oben links",
    rows: 3,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 2, h: 2 },
      { x: 2, y: 0, w: 1, h: 1 },
      { x: 2, y: 1, w: 1, h: 1 },
      { x: 0, y: 2, w: 1, h: 1 },
      { x: 1, y: 2, w: 1, h: 1 },
      { x: 2, y: 2, w: 1, h: 1 },
    ],
  },
  {
    id: "corner-2x2-top-right",
    label: "3x3 Ecke: 2x2 oben rechts",
    rows: 3,
    cols: 3,
    slots: [
      { x: 1, y: 0, w: 2, h: 2 },
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 0, y: 2, w: 1, h: 1 },
      { x: 1, y: 2, w: 1, h: 1 },
      { x: 2, y: 2, w: 1, h: 1 },
    ],
  },
  {
    id: "corner-2x2-bottom-left",
    label: "3x3 Ecke: 2x2 unten links",
    rows: 3,
    cols: 3,
    slots: [
      { x: 0, y: 1, w: 2, h: 2 },
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 1, y: 0, w: 1, h: 1 },
      { x: 2, y: 0, w: 1, h: 1 },
      { x: 2, y: 1, w: 1, h: 1 },
      { x: 2, y: 2, w: 1, h: 1 },
    ],
  },
  {
    id: "corner-2x2-bottom-right",
    label: "3x3 Ecke: 2x2 unten rechts",
    rows: 3,
    cols: 3,
    slots: [
      { x: 1, y: 1, w: 2, h: 2 },
      { x: 0, y: 0, w: 1, h: 1 },
      { x: 1, y: 0, w: 1, h: 1 },
      { x: 2, y: 0, w: 1, h: 1 },
      { x: 0, y: 1, w: 1, h: 1 },
      { x: 0, y: 2, w: 1, h: 1 },
    ],
  },
  { id: "grid-2x1", label: "2 Felder (oben/unten)", rows: 2, cols: 1, slots: createGridSlots(2, 1) },
  { id: "grid-1x2", label: "2 Felder (links/rechts)", rows: 1, cols: 2, slots: createGridSlots(1, 2) },
  { id: "grid-2x2", label: "2 x 2", rows: 2, cols: 2, slots: createGridSlots(2, 2) },
  { id: "grid-3x3", label: "3 x 3", rows: 3, cols: 3, slots: createGridSlots(3, 3) },
  { id: "grid-2x3", label: "2 x 3", rows: 2, cols: 3, slots: createGridSlots(2, 3) },
  { id: "grid-3x2", label: "3 x 2", rows: 3, cols: 2, slots: createGridSlots(3, 2) },
  { id: "grid-4x3", label: "4 x 3", rows: 4, cols: 3, slots: createGridSlots(4, 3) },
  { id: "grid-1x4-square", label: "1 x 4 (quadratisch)", rows: 1, cols: 4, slots: createGridSlots(1, 4) },
  { id: "grid-4x1-square", label: "4 x 1 (quadratisch)", rows: 4, cols: 1, slots: createGridSlots(4, 1) },
  {
    id: "grid-4x1-tall2",
    label: "4 x 1 (2 Einheiten Höhe)",
    rows: 2,
    cols: 4,
    slots: [
      { x: 0, y: 0, w: 1, h: 2 },
      { x: 1, y: 0, w: 1, h: 2 },
      { x: 2, y: 0, w: 1, h: 2 },
      { x: 3, y: 0, w: 1, h: 2 },
    ],
  },
  {
    id: "grid-1x4-wide2",
    label: "1 x 4 (2 Einheiten Breite)",
    rows: 4,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 2, h: 1 },
      { x: 0, y: 1, w: 2, h: 1 },
      { x: 0, y: 2, w: 2, h: 1 },
      { x: 0, y: 3, w: 2, h: 1 },
    ],
  },
  {
    id: "grid-3x1-tall3",
    label: "3 x 1 (3 Einheiten Hoehe)",
    rows: 3,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 1, h: 3 },
      { x: 1, y: 0, w: 1, h: 3 },
      { x: 2, y: 0, w: 1, h: 3 },
    ],
  },
  {
    id: "grid-1x3-wide3",
    label: "1 x 3 (3 Einheiten Breite)",
    rows: 3,
    cols: 3,
    slots: [
      { x: 0, y: 0, w: 3, h: 1 },
      { x: 0, y: 1, w: 3, h: 1 },
      { x: 0, y: 2, w: 3, h: 1 },
    ],
  },
  {
    id: "grid-4x1-tall4",
    label: "4 x 1 (4 Einheiten Hoehe)",
    rows: 4,
    cols: 4,
    slots: [
      { x: 0, y: 0, w: 1, h: 4 },
      { x: 1, y: 0, w: 1, h: 4 },
      { x: 2, y: 0, w: 1, h: 4 },
      { x: 3, y: 0, w: 1, h: 4 },
    ],
  },
  {
    id: "grid-1x4-wide4",
    label: "1 x 4 (4 Einheiten Breite)",
    rows: 4,
    cols: 4,
    slots: [
      { x: 0, y: 0, w: 4, h: 1 },
      { x: 0, y: 1, w: 4, h: 1 },
      { x: 0, y: 2, w: 4, h: 1 },
      { x: 0, y: 3, w: 4, h: 1 },
    ],
  },
  {
    id: "grid-1x2-wide2",
    label: "1 x 2 (2 Einheiten Breite)",
    rows: 2,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 2, h: 1 },
      { x: 0, y: 1, w: 2, h: 1 },
    ],
  },
  {
    id: "grid-2x1-tall2",
    label: "2 x 1 (2 Einheiten Hoehe)",
    rows: 2,
    cols: 2,
    slots: [
      { x: 0, y: 0, w: 1, h: 2 },
      { x: 1, y: 0, w: 1, h: 2 },
    ],
  },
  {
    id: "triptych-vertical",
    label: "Triptychon vertikal",
    rows: 1,
    cols: 3,
    slots: createGridSlots(1, 3),
  },
  {
    id: "triptych-horizontal",
    label: "Triptychon horizontal",
    rows: 3,
    cols: 1,
    slots: createGridSlots(3, 1),
  },
  {
  id: "treppe-2x3",
  label: "Treppe 2x3",
  rows: 3,
  cols: 4,
  slots: [
    { x: 0, y: 0, w: 2, h: 1 },
    { x: 1, y: 1, w: 2, h: 1 },
    { x: 2, y: 2, w: 2, h: 1 },
  ],
},
{
  id: "kreis-hero-3x3",
  label: "Kreis-Hero 3x3",
  rows: 3,
  cols: 3,
  slots: [
    { x: 0, y: 0, w: 2, h: 2, shape: "circle" },
    { x: 2, y: 0, w: 1, h: 1 },
    { x: 2, y: 1, w: 1, h: 1 },
    { x: 2, y: 2, w: 1, h: 1 },
    { x: 1, y: 2, w: 1, h: 1 },
    { x: 0, y: 2, w: 1, h: 1 },
  ],
},
{
  id: "hexagon-madness",
  label: "Hexagon Madness",
  rows: 3,
  cols: 3,
  slots: [
    { x: 0, y: 0, w: 1, h: 1, shape: "hexagon" },
    { x: 2, y: 0, w: 1, h: 1, shape: "hexagon" },
    { x: 1, y: 0, w: 1, h: 1, shape: "hexagon" },
    { x: 1, y: 1, w: 1, h: 1, shape: "hexagon" },
    { x: 0, y: 2, w: 1, h: 1, shape: "hexagon" },
    { x: 2, y: 2, w: 1, h: 1, shape: "hexagon" },
  ],
},
{
  id: "raute",
  label: "Raute",
  rows: 2,
  cols: 2,
  slots: [
    { x: 0, y: 0, w: 1, h: 1, shape: "diamond" },
    { x: 1, y: 0, w: 1, h: 1, shape: "diamond" },
    { x: 0, y: 1, w: 1, h: 1, shape: "diamond" },
    { x: 1, y: 1, w: 1, h: 1, shape: "diamond" },
  ],
},
{
  id: "raute-6",
  label: "Raute 6",
  rows: 2,
  cols: 3,
  slots: [
    { x: 0, y: 0, w: 1, h: 1, shape: "diamond" },
    { x: 1, y: 0, w: 1, h: 1, shape: "diamond" },
    { x: 0, y: 1, w: 1, h: 1, shape: "diamond" },
    { x: 1, y: 1, w: 1, h: 1, shape: "diamond" },
    { x: 2, y: 0, w: 1, h: 1, shape: "diamond" },
    { x: 2, y: 1, w: 1, h: 1, shape: "diamond" },
  ],
},
{
  id: "focus-circle",
  label: "Focus Circle",
  rows: 3,
  cols: 3,
  slots: [
    { x: 1, y: 1, w: 1, h: 1, shape: "circle" },
    { x: 1, y: 0, w: 1, h: 1 },
    { x: 0, y: 1, w: 1, h: 1 },
    { x: 2, y: 1, w: 1, h: 1 },
    { x: 1, y: 2, w: 1, h: 1 },
  ],
},
{
  id: "diamond-cross-9",
  label: "Diamond Cross 9",
  rows: 3,
  cols: 3,
  slots: [
    { x: 1, y: 1, w: 1, h: 1, shape: "diamond" },
    { x: 1, y: 0, w: 1, h: 1, shape: "diamond" },
    { x: 0, y: 1, w: 1, h: 1, shape: "diamond" },
    { x: 2, y: 1, w: 1, h: 1, shape: "diamond" },
    { x: 1, y: 2, w: 1, h: 1, shape: "diamond" },
    { x: 0, y: 0, w: 1, h: 1 },
    { x: 2, y: 0, w: 1, h: 1 },
    { x: 0, y: 2, w: 1, h: 1 },
    { x: 2, y: 2, w: 1, h: 1 },
  ],
},
{
  id: "hex-flower-7",
  label: "Hex Flower 7",
  rows: 3,
  cols: 3,
  slots: [
    { x: 1, y: 1, w: 1, h: 1, shape: "hexagon" },
    { x: 1, y: 0, w: 1, h: 1, shape: "hexagon" },
    { x: 0, y: 1, w: 1, h: 1, shape: "hexagon" },
    { x: 2, y: 1, w: 1, h: 1, shape: "hexagon" },
    { x: 1, y: 2, w: 1, h: 1, shape: "hexagon" },
    { x: 0, y: 2, w: 1, h: 1, shape: "hexagon" },
    { x: 2, y: 2, w: 1, h: 1, shape: "hexagon" },
  ],
},
{
  id: "story-badge",
  label: "Story Badge",
  rows: 4,
  cols: 3,
  slots: [
    { x: 0, y: 0, w: 3, h: 3 },
    { x: 0, y: 3, w: 1, h: 1, shape: "circle" },
    { x: 2, y: 3, w: 1, h: 1, shape: "circle" },
  ],
},
{
  id: "rounded-magazine",
  label: "Rounded Magazine",
  rows: 3,
  cols: 3,
  slots: [
    { x: 0, y: 0, w: 3, h: 2, shape: "rounded-rect" },
    { x: 0, y: 2, w: 1, h: 1, shape: "rounded-rect" },
    { x: 1, y: 2, w: 1, h: 1, shape: "rounded-rect" },
    { x: 2, y: 2, w: 1, h: 1, shape: "rounded-rect" },
  ],
},
{
  id: "mosaic-mix-6",
  label: "Mosaic Mix 6",
  rows: 2,
  cols: 4,
  slots: [
    { x: 0, y: 0, w: 1, h: 2 },
    { x: 1, y: 0, w: 1, h: 2 },
    { x: 2, y: 0, w: 1, h: 1, shape: "circle" },
    { x: 3, y: 0, w: 1, h: 1, shape: "diamond" },
    { x: 2, y: 1, w: 1, h: 1, shape: "diamond" },
    { x: 3, y: 1, w: 1, h: 1, shape: "circle" },
  ],
},
{
  id: "honeycomb-7-classic",
  label: "Honeycomb 7",
  rows: 3,
  cols: 4,
  slots: [
    { x: 1, y: 0, w: 1, h: 1, shape: "hexagon" },
    { x: 2, y: 0, w: 1, h: 1, shape: "hexagon" },
    { x: 0, y: 1, w: 1, h: 1, shape: "hexagon" },
    { x: 1, y: 1, w: 1, h: 1, shape: "hexagon" },
    { x: 2, y: 1, w: 1, h: 1, shape: "hexagon" },
    { x: 1, y: 2, w: 1, h: 1, shape: "hexagon" },
    { x: 2, y: 2, w: 1, h: 1, shape: "hexagon" },
  ],
},
{
  id: "poster-frame",
  label: "Poster Frame",
  rows: 4,
  cols: 4,
  slots: [
    { x: 1, y: 1, w: 2, h: 2 },
    { x: 0, y: 0, w: 1, h: 1, shape: "circle" },
    { x: 3, y: 0, w: 1, h: 1, shape: "circle" },
    { x: 0, y: 3, w: 1, h: 1, shape: "circle" },
    { x: 3, y: 3, w: 1, h: 1, shape: "circle" },
  ],
},
{
  id: "1-x-3-2-einheiten-breite",
  label: "1 x 3 (2 Einheiten Breite)",
  rows: 3,
  cols: 2,
  slots: [
    { x: 0, y: 0, w: 2, h: 1 },
    { x: 0, y: 1, w: 2, h: 1 },
    { x: 0, y: 2, w: 2, h: 1 },
  ],
},
];

const PRESET_LABELS = Object.freeze({
  "mosaic-top1-bottom2": {
    de: "Oben 1, unten 2",
    en: "Top 1, bottom 2",
    fr: "En haut 1, en bas 2",
  },
  "mosaic-top2-bottom1": {
    de: "Oben 2, unten 1",
    en: "Top 2, bottom 1",
    fr: "En haut 2, en bas 1",
  },
  "mosaic-left1-right2": {
    de: "Links 1, rechts 2",
    en: "Left 1, right 2",
    fr: "A gauche 1, a droite 2",
  },
  "mosaic-left2-right1": {
    de: "Links 2, rechts 1",
    en: "Left 2, right 1",
    fr: "A gauche 2, a droite 1",
  },
  "mosaic-top1-bottom3": {
    de: "Oben 1, unten 3",
    en: "Top 1, bottom 3",
    fr: "En haut 1, en bas 3",
  },
  "mosaic-top3-bottom1": {
    de: "Oben 3, unten 1",
    en: "Top 3, bottom 1",
    fr: "En haut 3, en bas 1",
  },
  "story-left-main": {
    de: "Story links, rechts 2",
    en: "Story left, right 2",
    fr: "Story a gauche, 2 a droite",
  },
  "story-right-main": {
    de: "Story rechts, links 2",
    en: "Story right, left 2",
    fr: "Story a droite, 2 a gauche",
  },
  "story-center-main": {
    de: "Story Mitte, Seiten 4",
    en: "Story center, sides 4",
    fr: "Story centre, cotes 4",
  },
  "hero-plus-4": {
    de: "Hero + 4",
    en: "Hero + 4",
    fr: "Hero + 4",
  },
  "panorama-plus-3": {
    de: "Panorama + 3",
    en: "Panorama + 3",
    fr: "Panorama + 3",
  },
  "mosaic-5-asym": {
    de: "Mosaik 5 asymmetrisch",
    en: "Mosaic 5 asymmetric",
    fr: "Mosaique 5 asymetrique",
  },
  "social-cover-split": {
    de: "Social Cover Split",
    en: "Social Cover Split",
    fr: "Social Cover Split",
  },
  "grid-4x4-center-circle": {
    de: "4x4 mit Kreis Mitte",
    en: "4x4 with center circle",
    fr: "4x4 avec cercle central",
  },
  "hex-3": {
    de: "Hex 3",
    en: "Hex 3",
    fr: "Hexa 3",
  },
  "hex-6": {
    de: "Hex 6",
    en: "Hex 6",
    fr: "Hexa 6",
  },
  "hex-7-honeycomb": {
    de: "Hex 7 Wabe",
    en: "Hex 7 honeycomb",
    fr: "Hexa 7 ruche",
  },
  "hex-9-honeycomb": {
    de: "Hex 9 Wabe",
    en: "Hex 9 honeycomb",
    fr: "Hexa 9 ruche",
  },
  "corner-2x2-top-left": {
    de: "3x3 Ecke: 2x2 oben links",
    en: "3x3 corner: 2x2 top left",
    fr: "Coin 3x3: 2x2 en haut a gauche",
  },
  "corner-2x2-top-right": {
    de: "3x3 Ecke: 2x2 oben rechts",
    en: "3x3 corner: 2x2 top right",
    fr: "Coin 3x3: 2x2 en haut a droite",
  },
  "corner-2x2-bottom-left": {
    de: "3x3 Ecke: 2x2 unten links",
    en: "3x3 corner: 2x2 bottom left",
    fr: "Coin 3x3: 2x2 en bas a gauche",
  },
  "corner-2x2-bottom-right": {
    de: "3x3 Ecke: 2x2 unten rechts",
    en: "3x3 corner: 2x2 bottom right",
    fr: "Coin 3x3: 2x2 en bas a droite",
  },
  "grid-2x1": {
    de: "2 Felder (oben/unten)",
    en: "2 slots (top/bottom)",
    fr: "2 cases (haut/bas)",
  },
  "grid-1x2": {
    de: "2 Felder (links/rechts)",
    en: "2 slots (left/right)",
    fr: "2 cases (gauche/droite)",
  },
  "grid-2x2": {
    de: "2 x 2",
    en: "2 x 2",
    fr: "2 x 2",
  },
  "grid-3x3": {
    de: "3 x 3",
    en: "3 x 3",
    fr: "3 x 3",
  },
  "grid-2x3": {
    de: "2 x 3",
    en: "2 x 3",
    fr: "2 x 3",
  },
  "grid-3x2": {
    de: "3 x 2",
    en: "3 x 2",
    fr: "3 x 2",
  },
  "grid-4x3": {
    de: "4 x 3",
    en: "4 x 3",
    fr: "4 x 3",
  },
  "grid-1x4-square": {
    de: "1 x 4 (quadratisch)",
    en: "1 x 4 (square)",
    fr: "1 x 4 (carre)",
  },
  "grid-4x1-square": {
    de: "4 x 1 (quadratisch)",
    en: "4 x 1 (square)",
    fr: "4 x 1 (carre)",
  },
  "grid-4x1-tall2": {
    de: "4 x 1 (2 Einheiten Höhe)",
    en: "4 x 1 (2 units height)",
    fr: "4 x 1 (hauteur 2 unites)",
  },
  "grid-1x4-wide2": {
    de: "1 x 4 (2 Einheiten Breite)",
    en: "1 x 4 (2 units width)",
    fr: "1 x 4 (largeur 2 unites)",
  },
  "grid-3x1-tall3": {
    de: "3 x 1 (3 Einheiten Hoehe)",
    en: "3 x 1 (3 units height)",
    fr: "3 x 1 (hauteur 3 unites)",
  },
  "grid-1x3-wide3": {
    de: "1 x 3 (3 Einheiten Breite)",
    en: "1 x 3 (3 units width)",
    fr: "1 x 3 (largeur 3 unites)",
  },
  "grid-4x1-tall4": {
    de: "4 x 1 (4 Einheiten Hoehe)",
    en: "4 x 1 (4 units height)",
    fr: "4 x 1 (hauteur 4 unites)",
  },
  "grid-1x4-wide4": {
    de: "1 x 4 (4 Einheiten Breite)",
    en: "1 x 4 (4 units width)",
    fr: "1 x 4 (largeur 4 unites)",
  },
  "grid-1x2-wide2": {
    de: "1 x 2 (2 Einheiten Breite)",
    en: "1 x 2 (2 units width)",
    fr: "1 x 2 (largeur 2 unites)",
  },
  "grid-2x1-tall2": {
    de: "2 x 1 (2 Einheiten Hoehe)",
    en: "2 x 1 (2 units height)",
    fr: "2 x 1 (hauteur 2 unites)",
  },
  "triptych-vertical": {
    de: "Triptychon vertikal",
    en: "Triptych vertical",
    fr: "Triptyque vertical",
  },
  "triptych-horizontal": {
    de: "Triptychon horizontal",
    en: "Triptych horizontal",
    fr: "Triptyque horizontal",
  },"treppe-2x3": {
  de: "Treppe 2x3",
  en: "Stairs 2x3",
  fr: "Escalier 2x3",
},
"kreis-hero-3x3": {
  de: "Kreis-Hero 3x3",
  en: "Circle Hero 3x3",
  fr: "Circle Hero 3x3",
},
"hexagon-madness": {
  de: "Hexagon Madness",
  en: "Hexagon Madness",
  fr: "Hexagon Madness",
},
"raute": {
  de: "Raute",
  en: "diamond",
  fr: "losange",
},
"raute-6": {
  de: "Raute 6",
  en: "diamond 6",
  fr: "losange 6",
},
"focus-circle": {
  de: "Fokus-Kreis",
  en: "Focus circle",
  fr: "Cercle focus",
},
"diamond-cross-9": {
  de: "Rauten-Kreuz 9",
  en: "Diamond cross 9",
  fr: "Croix losange 9",
},
"hex-flower-7": {
  de: "Hex-Blume 7",
  en: "Hex flower 7",
  fr: "Fleur hex 7",
},
"story-badge": {
  de: "Story-Badge",
  en: "Story badge",
  fr: "Badge story",
},
"rounded-magazine": {
  de: "Rounded Magazine",
  en: "Rounded magazine",
  fr: "Magazine arrondi",
},
"mosaic-mix-6": {
  de: "Mosaik-Mix 6",
  en: "Mosaic mix 6",
  fr: "Mosaique mix 6",
},
"honeycomb-7-classic": {
  de: "Wabe 7",
  en: "Honeycomb 7",
  fr: "Ruche 7",
},
"poster-frame": {
  de: "Poster-Rahmen",
  en: "Poster frame",
  fr: "Cadre poster",
},
"1-x-3-2-einheiten-breite": {
  de: "1 x 3 (2 Einheiten Breite)",
  en: "1 x 3 (2 units width)",
  fr: "1 x 3 (largeur 2 unites)",
},
});

  window.FOTOCOLLAGE_TEMPLATE_CONFIG = { PRESETS, PRESET_LABELS };
})();
