(() => {
  const DAILY_TIPS = Object.freeze({
    de: [
      "Wasserzeichen kannst du in den Einstellungen aktivieren und dauerhaft speichern.",
      "Mit Hex-Pack wirken Hexagon- und Rauten-Layouts oft deutlich kompakter.",
      "In Schritt 3 kannst du Bilder direkt in der Vorschau verschieben und zoomen.",
      "Mit Sortieren kannst du Bilder schnell zwischen Feldern tauschen.",
      "Texte lassen sich pro Feld frei platzieren, auch per Drag-and-drop.",
      "Fuer Social Posts helfen Export-Presets mit passendem Seitenverhaeltnis.",
      "Fuer Link-Vorschauen nutze Open Graph / Twitter (1200x630).",
      "GIF eignet sich am besten mit Breiten zwischen 480 und 800 Pixeln.",
      "Bei GIF bestimmt der Sekunden-Slider, wie lange jedes Bild angezeigt wird.",
      "Leere Felder uebernehmen automatisch die eingestellte Hintergrundfarbe.",
      "Mit Neustart beginnst du sofort neu, ohne Abstand, Randabstand und Hintergrund zu verlieren.",
      "Die Browser-Sprache wird automatisch erkannt, kann aber in den Einstellungen geaendert werden.",
      "EXIF-Felder werden nur beim JPEG-Export geschrieben (wenn aktiviert).",
      "Der Wasserzeichen-Text kann auch als EXIF-UserComment uebernommen werden.",
      "Fuer Story/Reel-Formate funktionieren vertikale Vorlagen wie 1x3 oder 1x4 besonders gut.",
      "Wenn ein Text zu gross ist, zeigt die App eine Warnung fuer den sichtbaren Bereich.",
      "Auf Mobilgeraeten kannst du in der Vorschau mit Pinch zoomen und mit einem Finger verschieben.",
      "Auf dem Desktop zoomst du im aktiven Feld bequem mit dem Mausrad.",
      "Beim Wechsel von Social-Preset zurueck auf Frei setzt die App die Breite wieder passend zur Collage.",
      "Fuer klare Bildkanten nutze kleine Abstaende und einen etwas groesseren Randabstand.",
      "Fuer ruhige Collagen funktioniert ein einheitlicher Hintergrund oft besser als starke Farben.",
      "Mit Rounded-Rect wirken Collagen weicher, mit Raute oder Hexagon dynamischer.",
      "Ein zentrales Motiv wirkt staerker, wenn die umliegenden Slots kleinere Detailbilder zeigen.",
      "Fuer Instagram Feed ist 4:5 oft wirkungsvoller als 1:1.",
      "Fuer X und LinkedIn funktionieren breite Presets mit klarer Motivmitte besonders gut.",
      "Fuer Pinterest wirken vertikale Formate (2:3) oft am besten.",
      "Vor dem Export lohnt ein kurzer Check der Safe Area bei Social-Presets.",
      "Texte sind am lesbarsten mit hohem Kontrast zur Bildflaeche.",
      "Setze Schriftgroessen pro Feld unterschiedlich, um Blickfuehrung zu erzeugen.",
      "Wenn ein Bild zu stark beschnitten ist, zuerst rauszoomen, dann neu positionieren.",
      "In Hex-Pack kannst du mit den 4 Hex-Slidern Abstand und Feldgroesse fein abstimmen.",
      "Bei GIF besser mit weniger Frames starten, dann bei Bedarf erweitern.",
      "PDF eignet sich gut, wenn die Collage ohne Qualitaetsverlust weitergegeben wird.",
      "PNG ist ideal, wenn du spaeter noch weiterbearbeiten moechtest.",
      "JPEG ist sinnvoll, wenn Dateigroesse wichtiger ist als absolute Detailtreue.",
      "Ein dezentes Wasserzeichen unten rechts stoert oft am wenigsten im Motiv.",
    ],
    en: [
      "You can enable and persist a watermark in settings.",
      "With Hex pack, hexagon and diamond layouts often look much more compact.",
      "In step 3, you can move and zoom images directly in the preview.",
      "Use Sort to quickly swap images between slots.",
      "Text can be freely placed per slot, including drag and drop.",
      "For social posts, export presets with matching aspect ratios are very helpful.",
      "For link previews, use Open Graph / Twitter (1200x630).",
      "GIF works best with widths between 480 and 800 pixels.",
      "For GIF, the seconds slider controls how long each frame is shown.",
      "Empty slots automatically use your selected background color.",
      "With Restart, you can start over without losing spacing, outer gap, and background.",
      "Browser language is detected automatically, but can be changed in settings.",
      "EXIF fields are written only for JPEG export (when enabled).",
      "The watermark text can also be written as EXIF UserComment.",
      "For Story/Reel formats, vertical templates like 1x3 or 1x4 work especially well.",
      "If text is too large, the app warns you about visible-area overflow.",
      "On mobile, use pinch to zoom and one finger to move in the preview.",
      "On desktop, use the mouse wheel to zoom in the active slot.",
      "When switching from a social preset back to Free, width resets to match the collage.",
      "For crisp edges, use small spacing and a slightly larger outer gap.",
      "For calmer collages, a consistent background often works better than strong colors.",
      "Rounded-rect feels softer; diamond or hexagon feels more dynamic.",
      "A centered hero image is stronger when surrounding slots show smaller details.",
      "For Instagram feed, 4:5 is often more effective than 1:1.",
      "For X and LinkedIn, wide presets with a clear center focus work best.",
      "For Pinterest, vertical formats (2:3) often perform best.",
      "Before export, do a quick Safe Area check for social presets.",
      "Text is easiest to read with strong contrast against the image.",
      "Use different font sizes per slot to guide the viewer's eye.",
      "If an image is cropped too much, zoom out first, then reposition.",
      "In Hex pack, fine-tune spacing and tile size with the 4 hex sliders.",
      "For GIF, start with fewer frames, then add more if needed.",
      "PDF is great when you need to share without quality loss.",
      "PNG is ideal if you plan to edit further afterward.",
      "JPEG is useful when file size matters more than absolute detail.",
      "A subtle bottom-right watermark often distracts the least.",
    ],
    fr: [
      "Vous pouvez activer et memoriser un filigrane dans les parametres.",
      "Avec le mode Hex-pack, les mises en page hexagonales et losanges paraissent souvent plus compactes.",
      "A l'etape 3, vous pouvez deplacer et zoomer les images directement dans l'aperçu.",
      "Utilisez Trier pour echanger rapidement des images entre les emplacements.",
      "Le texte peut etre place librement dans chaque case, y compris par glisser-deposer.",
      "Pour les posts sociaux, les presets d'export au bon ratio sont tres utiles.",
      "Pour les aperçus de liens, utilisez Open Graph / Twitter (1200x630).",
      "Le GIF fonctionne le mieux avec une largeur entre 480 et 800 pixels.",
      "Pour le GIF, le curseur des secondes definit la duree d'affichage de chaque image.",
      "Les cases vides utilisent automatiquement la couleur d'arriere-plan choisie.",
      "Avec Redemarrer, vous recommencez sans perdre l'espacement, la marge externe et l'arriere-plan.",
      "La langue du navigateur est detectee automatiquement, mais reste modifiable dans les parametres.",
      "Les champs EXIF sont ecrits uniquement pour l'export JPEG (si active).",
      "Le texte du filigrane peut aussi etre ecrit en EXIF UserComment.",
      "Pour Story/Reel, les modeles verticaux comme 1x3 ou 1x4 sont souvent ideaux.",
      "Si le texte est trop grand, l'application avertit quand il depasse la zone visible.",
      "Sur mobile, utilisez le pincement pour zoomer et un doigt pour deplacer dans l'aperçu.",
      "Sur desktop, utilisez la molette pour zoomer dans la case active.",
      "En revenant d'un preset social vers Libre, la largeur est reajustee a la collage.",
      "Pour des bords nets, utilisez un faible espacement et une marge externe un peu plus grande.",
      "Pour des collages plus calmes, un fond uniforme fonctionne souvent mieux que des couleurs fortes.",
      "Rounded-rect donne un style doux, losange ou hexagone un style plus dynamique.",
      "Un visuel central fort marche mieux avec de petites images detail autour.",
      "Pour Instagram feed, le 4:5 est souvent plus efficace que le 1:1.",
      "Pour X et LinkedIn, les presets larges avec un centre clair fonctionnent bien.",
      "Pour Pinterest, les formats verticaux (2:3) sont souvent les plus adaptes.",
      "Avant export, faites un controle rapide de la Safe Area pour les presets sociaux.",
      "Le texte est plus lisible avec un contraste fort par rapport a l'image.",
      "Variez les tailles de police selon les cases pour guider le regard.",
      "Si une image est trop recadree, dezoomez d'abord puis repositionnez.",
      "En Hex-pack, affinez espacement et taille des cases avec les 4 curseurs hex.",
      "Pour le GIF, commencez avec peu d'images, puis augmentez si besoin.",
      "Le PDF est ideal pour partager sans perte de qualite.",
      "Le PNG est ideal si vous voulez retoucher ensuite.",
      "Le JPEG est pertinent quand la taille du fichier prime sur le detail maximal.",
      "Un filigrane discret en bas a droite est souvent le moins genant.",
    ],
  });

  window.FOTOCOLLAGE_TIPS_CONFIG = { DAILY_TIPS };
})();
